# Generated by Django 3.0.5 on 2023-08-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Auther',
        ),
    ]
