# Generated by Django 3.0.5 on 2023-08-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
