# Generated by Django 3.0.5 on 2023-08-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230812_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
