# Generated by Django 3.0.5 on 2023-08-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230812_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
